# Site settings
title: nullday
email: chris@nullday.de
description: "nullday ist der private webspace von Christian Rebischke. Letzte Ver√§nderung: 2017-04-25"
baseurl: ""
url: "http://www.nullday.de"
twitter_username: sh1bumi
github_username:  shibumi
linkedin_username: shibumi
google_plus_username: ChristianRebischke
xing_username: Christian_Rebischke

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
